<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dsktcuczh/image/upload/v1554314737/670e022a-f530-458c-ac9e-176a15d77ece.png" alt="Leah Jaja">
                        <h6>Leah Jaja</h6>
                        <p>Full Stack developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/pwettyleah" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/leahjaja" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@leahjaja12" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                           Leah Jaja is an enthusiast web developer passionate about building applications that are user-friendly, 
                           interactive, reliable, and efficient. Leah is inspired by women making a adifference around the world.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | SQL</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
